//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VsInsideManagement
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class VsInsideDBEntities : DbContext
    {
        private static VsInsideDBEntities content;
        
        public VsInsideDBEntities()
            : base("name=VsInsideDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
        
        public static VsInsideDBEntities Content()
        {
            return content = new VsInsideDBEntities();
        }
    
        public virtual DbSet<Buyer> Buyer { get; set; }
        public virtual DbSet<Color> Color { get; set; }
        public virtual DbSet<DelAddress> DelAddress { get; set; }
        public virtual DbSet<Delivery> Delivery { get; set; }
        public virtual DbSet<Discount> Discount { get; set; }
        public virtual DbSet<Making> Making { get; set; }
        public virtual DbSet<Manager> Manager { get; set; }
        public virtual DbSet<Material> Material { get; set; }
        public virtual DbSet<Packaging> Packaging { get; set; }
        public virtual DbSet<ProdType> ProdType { get; set; }
        public virtual DbSet<Product> Product { get; set; }
        public virtual DbSet<SetOrder> SetOrder { get; set; }
        public virtual DbSet<Shop> Shop { get; set; }
        public virtual DbSet<Size> Size { get; set; }
        public virtual DbSet<Supply> Supply { get; set; }
    }
}
