//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InfoSystemDB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class InfoSystemDBEntities : DbContext
    {
        private static InfoSystemDBEntities content;
        
        public InfoSystemDBEntities()
            : base("name=InfoSystemDBEntities")
        {
        }

        public static InfoSystemDBEntities GetContent()
        {
            if (content == null)
                content = new InfoSystemDBEntities();
            return content;
        }

        public static InfoSystemDBEntities Reload()
        {
            return content = new InfoSystemDBEntities();
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Adress> Adress { get; set; }
        public virtual DbSet<Buyers> Buyers { get; set; }
        public virtual DbSet<Colors> Colors { get; set; }
        public virtual DbSet<Delivery> Delivery { get; set; }
        public virtual DbSet<Discounts> Discounts { get; set; }
        public virtual DbSet<Making> Making { get; set; }
        public virtual DbSet<Managers> Managers { get; set; }
        public virtual DbSet<Materials> Materials { get; set; }
        public virtual DbSet<Orders> Orders { get; set; }
        public virtual DbSet<Packaging> Packaging { get; set; }
        public virtual DbSet<Products> Products { get; set; }
        public virtual DbSet<Shops> Shops { get; set; }
        public virtual DbSet<Sizes> Sizes { get; set; }
        public virtual DbSet<Supply> Supply { get; set; }
        public virtual DbSet<Tips> Tips { get; set; }
    }
}
