//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InfoSystemDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Making
    {
        public int id { get; set; }
        public int sup { get; set; }
        public int prod { get; set; }
        public int amount { get; set; }
    
        public virtual Products Products { get; set; }
        public virtual Supply Supply { get; set; }
    }
}
